//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public Links()
        {
            this.Tokens = new HashSet<Tokens>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long Follows { get; set; }
        public string ShortUrl { get; set; }
    
        public virtual ICollection<Tokens> Tokens { get; set; }
    }
}
