//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenMapping
    {
        public int LinkId { get; set; }
        public int TokenId { get; set; }
        public long MapId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Links Links { get; set; }
        public virtual Tokens Tokens { get; set; }
    }
}
